# Generated by Django 5.2.1 on 2025-06-18 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_timer_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.taskdescription'),
        ),
    ]
