# Generated by Django 5.2.1 on 2025-06-18 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_timer_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timer',
            old_name='tag',
            new_name='task',
        ),
    ]
