# Generated by Django 5.2.1 on 2025-06-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_tag_timer_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdescription',
            name='is_conplete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
