# Generated by Django 5.2.1 on 2025-06-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_taskdescription_is_conplete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdescription',
            old_name='is_conplete',
            new_name='is_complete',
        ),
    ]
