# Generated by Django 5.2.1 on 2025-06-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_is_conplete_taskdescription_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdescription',
            name='due_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timer',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
