# Generated by Django 5.2.1 on 2025-06-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_pet_name_userprofile_pet_profile_delete_userstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
        migrations.AddField(
            model_name='pet',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
