# Generated by Django 5.2.1 on 2025-06-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_pet_image_pet_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='hunger_level',
        ),
    ]
