# Generated by Django 5.2.1 on 2025-06-21 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_remove_userprofile_published_timer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='happiness_level',
            new_name='affirmation_level',
        ),
    ]
