# Generated by Django 5.2.1 on 2025-06-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_rename_happiness_level_pet_affirmation_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='affirmation_level',
            new_name='affection_level',
        ),
    ]
