# Generated by Django 5.2.1 on 2025-06-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_rename_affirmation_level_pet_affection_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktag',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
